//! M7.7 ISO install-to-disk scaffold / package gate (outside Proven Core).
//!
//! Pillar: [Z] [A]
//! Proven Core: **outside** (ADR-009)
//!
//! Proves runbook + evidence template + install package exist.
//! Does **not** print `RAYNU-V-M7-ISO-INSTALL-OK` from host/CI — that marker
//! is reserved for QEMU/iron install-to-disk + reboot-to-disk proof.

use super::iso_install::{
    install_launch_surfaces_present, prop_iso_install_lab_package, prop_iso_install_package,
    prop_iso_reboot_lab_package, ISO_INSTALL_GAP_NOTE, ISO_INSTALL_HOST_LIMIT_NOTE,
    ISO_INSTALL_MVP_NOTE, M7_ISO_INSTALL_OK_MARKER, M7_ISO_INSTALL_SCAFFOLD_MARKER,
};

/// Host / CI marker when the M7.7 scaffold package passes.
pub const M7_ISO_INSTALL_GATE_MARKER: &str = M7_ISO_INSTALL_SCAFFOLD_MARKER;

/// True when iso_install module exposes package + markers + closed GAP.
pub fn iso_install_surface_present() -> bool {
    let s = include_str!("iso_install.rs");
    s.contains("fn prop_iso_install_package(")
        && s.contains("fn begin_install_to_disk(")
        && s.contains("fn launch_contract(")
        && s.contains("fn arm_install_launch_contract(")
        && s.contains("fn arm_lab_install_contract(")
        && s.contains("fn disk_bytes_for_virtio_launch(")
        && s.contains("fn note_reboot_pending_lab(")
        && s.contains("fn probe_iso_install_lab_flag(")
        && s.contains("fn probe_iso_reboot_lab_flag(")
        && s.contains("fn probe_iso_persist_reboot(")
        && s.contains("fn probe_product_linux_iso(")
        && s.contains("fn present_product_iso_if_retained(")
        && s.contains("fn stage46_hold_e4_shell(")
        && s.contains("fn retain_product_iso_bytes(")
        && s.contains("fn persist_armed_install_to_esp(")
        && s.contains("fn fill_persist_image(")
        && s.contains("fn prop_iso_reboot_lab_package(")
        && s.contains("fn mark_disk_written(")
        && s.contains("fn mark_reboot_pending(")
        && s.contains("fn mark_booted_from_disk(")
        && s.contains("fn dispatch_iso_install_rest(")
        && s.contains("fn product_iso_continues_past_eltorito(")
        && s.contains("fn stage46_host_never_prints_iso_install_ok(")
        && s.contains(M7_ISO_INSTALL_OK_MARKER)
        && s.contains(M7_ISO_INSTALL_SCAFFOLD_MARKER)
        && s.contains(ISO_INSTALL_GAP_NOTE)
        && s.contains(ISO_INSTALL_MVP_NOTE)
        && ISO_INSTALL_GAP_NOTE.contains("CLOSED M7.7")
        && include_str!("../src/main.rs").contains("disk_bytes_for_virtio_launch")
        && include_str!("../src/main.rs").contains("E5 install-sized virtio-blk")
        && include_str!("../src/main.rs").contains("probe_iso_install_lab_flag")
        && include_str!("../src/main.rs").contains("probe_iso_reboot_lab_flag")
        && include_str!("../src/main.rs").contains("probe_product_linux_iso")
        && include_str!("../src/main.rs").contains("stage46_hold_e4_shell")
        && include_str!("../tools/run-qemu.sh").contains("PRODUCT_ISO")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("--linux-iso")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("--no-linux-iso")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("pruning leftover ESP ISOs")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("ESP free=")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("fsck.vfat -a")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("not format")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("--refat-cruzer")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("mkfs.vfat -I -F 32 -n")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("fat_bytes_too_small")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("re-run with --refat-cruzer")
        && include_str!("../devices/guest_irq.rs").contains("fn take_inject_vector(")
        && include_str!("../devices/guest_irq.rs").contains("VIRTIO_GSI")
        && include_str!("../devices/guest_irq.rs").contains("VIRTIO_ISO_GSI")
        && include_str!("../devices/guest_irq.rs").contains("raise_gsi(VIRTIO_PIC_IRQ)")
        && include_str!("../devices/guest_irq.rs").contains("fn raise_pit(")
        && include_str!("../devices/guest_irq.rs").contains("fn take_ioapic_vector(")
        && include_str!("../devices/guest_irq.rs").contains("fn ioapic_eoi(")
        && include_str!("../devices/guest_irq.rs").contains("RTE_REMOTE_IRR")
        && include_str!("../devices/lapic_virt.rs").contains("fn latch_irr(")
        && include_str!("../vmx/guest_uefi.rs").contains("take_ioapic_vector()")
        && include_str!("../devices/guest_irq.rs").contains("PIT_IRQ")
        && include_str!("../devices/guest_platform.rs").contains("fn pit_tick(")
        && include_str!("../devices/guest_platform.rs").contains("fn pit_write_data(")
        && include_str!("../devices/guest_platform.rs").contains("pit_access")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub rex:")
        && include_str!("../vmx/guest_uefi.rs").contains("try_inject_guest_irq")
        && include_str!("../vmx/guest_uefi.rs").contains("raise_pit()")
        && include_str!("../vmx/guest_uefi.rs").contains("ept_install_ioapic_trap")
        && include_str!("../vmx/guest_uefi.rs").contains("handle_uart_product")
        && include_str!("../devices/guest_uart.rs").contains("fn reassert_irq(")
        && include_str!("../devices/guest_uart.rs").contains("fn poll_host_rx(")
        && include_str!("../boot/serial.rs").contains("fn try_read_byte(")
        && include_str!("iso_install.rs").contains("fn patch_iso_linux_serial_console(")
        && include_str!("iso_install.rs").contains("squashfs,virtio_blk console=ttyS0")
        && include_str!("iso_install.rs").contains("console=tty0")
        && include_str!("../vmx/guest_uefi.rs").contains("fn copy_guest_linear_one_page(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn copy_flash_at(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_flash_off(")
        && include_str!("../vmx/guest_uefi.rs").contains("FLASH_HPA")
        && include_str!("../vmx/guest_uefi.rs").contains("fn xapic_fetch_miss_eax_fallback(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_insn_linear(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn copy_mmio_insn(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_mmio_skip_len(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_decoded_len(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_effective_len(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn try_alloc_product_iso_install_disk(")
        && include_str!("../vmx/guest_uefi.rs").contains("Reserve the install disk first")
        && include_str!("iso_install.rs").contains("fn product_iso_install_disk_try_sizes(")
        && include_str!("iso_install.rs").contains("fn product_iso_frame_pool_prefer_end(")
        && include_str!("../boot/handoff.rs").contains("frame pool product-ISO iron")
        && include_str!("../arch/cpu.rs").contains("fn host_hypervisor_present(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_insn_bytes_this_page(")
        && include_str!("iso_install.rs").contains("ata_piix,loop,sr-mod")
        && include_str!("iso_install.rs").contains("alpine_dev=vdb")
        && include_str!("iso_install.rs").contains("terminal_output serial ")
        && include_str!("iso_install.rs").contains("set timeout=1")
        && include_str!("iso_install.rs").contains("insmod efi_gop")
        && include_str!("iso_install.rs").contains("insmod all_video")
        && include_str!("iso_install.rs").contains("terminal_output console")
        && include_str!("../vmx/guest_uefi.rs").contains("fn handle_xapic_ept(")
        && include_str!("../vmx/guest_uefi.rs").contains("xAPIC 4K trap")
        && include_str!("../devices/lapic_virt.rs").contains("fn poll_timer_expiry(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_ADD")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SUB")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub cmp_reg_left:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub alu_reg_left:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_NOT")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_ADC")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SBB")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SHL")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_shift_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_shift(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_cc_taken(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_apply_cc(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_BSF")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_HINT")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_scan_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_hint(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_scan(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_TZCNT")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_tzcnt_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_count_zero(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_POPCNT")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_popcnt(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_PUSH")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_stack_width(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_stack_push(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_push(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_pop(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_MOVS")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_alu_is_string(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_CMPS")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SCAS")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SSE")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_alu_is_sse(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_sse_from_mem(")
        && include_str!("../vmx/guest_uefi.rs").contains("SAVED_XMM")
        && include_str!("../vmx/guest_uefi.rs").contains("movdqu")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_sse(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_xmm_in(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_string_step(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_IMUL")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_imul_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_imul(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_MUL")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_mul_pair_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_mul_pair(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_DIV")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_div_apply(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_DIV_DE_INTR_INFO")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MOVNTI")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_div_pair(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn inject_mmio_div_de(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SHLD")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_double_shift_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_double_shift(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_alu_apply_cf(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_apply_cf(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_alu_rflags(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_alu_result(")
        && include_str!("../vmx/guest_uefi.rs").contains("armed product ISO uses")
        && include_str!("../vmx/guest_uefi.rs").contains("QEMU `PRODUCT_ISO=` can pass OVMF StartImage")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub bt:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_bt_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_apply_bt(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_CMPXCHG")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_CMPXCHG8B")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_cmpxchg8b_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_apply_atomic(")
        && include_str!("../vmx/fields.rs").contains("CPU_BASED_CR8_LOAD_EXITING")
        && include_str!("../vmx/guest_uefi.rs").contains("CPU_BASED_CR8_STORE_EXITING")
        && include_str!("../devices/lapic_virt.rs").contains("fn set_cr8(")
        && include_str!("../vmx/guest_uefi.rs").contains("(8, 0)")
        && include_str!("../vmx/guest_uefi.rs").contains("| CPU_BASED_CR8_LOAD_EXITING")
        && !include_str!("../vmx/launch.rs").contains("| CPU_BASED_CR8_LOAD_EXITING")
        && include_str!("../devices/guest_serial_answer.rs").contains("mount -t iso9660 /dev/vdb")
        && include_str!("../devices/guest_serial_answer.rs").contains("mkdir -p /media/cdrom")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub test:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_test_rflags(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_apply_test_cmp(")
        && include_str!("../devices/guest_serial_answer.rs").contains("Stay in CONFIRM")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub xchg:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_AND")
        && include_str!("../devices/ide_cdrom.rs").contains("31 * ISO_SECTOR")
        && include_str!("../devices/ide_cdrom.rs").contains("ATA_DEVCTL_NIEN")
        && include_str!("../devices/guest_virtio_blk.rs").contains("DATA_SEGS")
        && include_str!("../devices/guest_virtio_blk.rs").contains("GUEST_VIRTIO_ISO_PCI_DEV")
        && include_str!("../devices/guest_virtio_blk.rs").contains("VIRTIO_BLK_F_RO")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn page_left(")
        && include_str!("../devices/guest_serial_answer.rs").contains("fn note_tx(")
        && include_str!("../devices/guest_serial_answer.rs").contains("/ # ")
        && include_str!("../devices/guest_serial_answer.rs").contains("setup-disk -m sys -s 0 /dev/vda")
        && include_str!("../devices/guest_serial_answer.rs").contains("Which disk")
        && include_str!("../devices/guest_serial_answer.rs").contains("No disks available")
        && include_str!("../devices/guest_serial_answer.rs").contains("/media/cdrom/apks")
        && include_str!("../devices/guest_serial_answer.rs").contains("> /etc/apk/repositories")
        && include_str!("../devices/guest_serial_answer.rs").contains("How would you like")
        && include_str!("../devices/guest_serial_answer.rs").contains("modprobe virtio_pci")
        && include_str!("../devices/guest_serial_answer.rs").contains("modprobe sr_mod")
        && include_str!("../devices/guest_serial_answer.rs").contains("modprobe isofs")
        && include_str!("../devices/guest_serial_answer.rs").contains("mdev -s")
        && include_str!("../devices/guest_serial_answer.rs").contains("sleep 1")
        && include_str!("../devices/guest_serial_answer.rs").contains("[ -b /dev/vda ]")
        && include_str!("../devices/guest_serial_answer.rs").contains("|| mount -t iso9660 /dev/sr0")
        && include_str!("../vmx/guest_uefi.rs").contains("Lazy 2MiB WB map")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_near_xfer(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_CALL")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_JMP")
        && include_str!("../devices/guest_serial_answer.rs").contains("BOOTLOADER=grub")
        && include_str!("../devices/guest_serial_answer.rs").contains("USE_EFI=1")
        && include_str!("../devices/guest_serial_answer.rs").contains("BOOT_SIZE=48")
        && include_str!("../devices/guest_serial_answer.rs").contains("bootloader?")
        && include_str!("../devices/guest_serial_answer.rs").contains("[y/N]")
        && include_str!("../devices/guest_serial_answer.rs").contains("fn is_yes_prompt(")
        && prop_iso_install_lab_package()
        && prop_iso_reboot_lab_package()
}

/// True when honesty + launch surfaces hold.
pub fn iso_install_honesty_holds() -> bool {
    ISO_INSTALL_HOST_LIMIT_NOTE.contains("cannot close")
        && ISO_INSTALL_MVP_NOTE.contains("reboot-to-disk")
        && M7_ISO_INSTALL_OK_MARKER == "RAYNU-V-M7-ISO-INSTALL-OK"
        && M7_ISO_INSTALL_SCAFFOLD_MARKER == "RAYNU-V-M7-ISO-INSTALL-SCAFFOLD-OK"
        && crate::mgmt::iso_install::stage46_host_never_prints_iso_install_ok()
        && crate::mgmt::iso_install::product_iso_continues_past_eltorito(false, true)
        && !crate::mgmt::iso_install::product_iso_continues_past_eltorito(true, true)
        && !crate::mgmt::iso_install::product_iso_len_is_window(
            crate::devices::ide_cdrom::GUEST_CD_ISO_CAP,
        )
        && crate::mgmt::iso_install::product_iso_len_is_window(
            crate::devices::ide_cdrom::GUEST_CD_ISO_CAP + 2048,
        )
        && install_launch_surfaces_present()
}

/// True when runbook + smoke + evidence template exist with required phrases.
pub fn iso_install_scripts_present() -> bool {
    let smoke = include_str!("../tools/m7-iso-install-smoke.sh");
    let runbook = include_str!("../docs/runbooks/iso_install.md");
    let evidence = include_str!("../docs/evidence/r640/TEMPLATE-iso-install.md");
    let status = include_str!("../docs/evidence/r640/STATUS-iso-install");
    smoke.contains(M7_ISO_INSTALL_SCAFFOLD_MARKER)
        && smoke.contains("m7_7_iso_install_scaffold_passes")
        && smoke.contains(M7_ISO_INSTALL_OK_MARKER)
        && smoke.contains("never print iron marker")
        && runbook.contains(M7_ISO_INSTALL_OK_MARKER)
        && runbook.contains(M7_ISO_INSTALL_SCAFFOLD_MARKER)
        && runbook.contains("reboot-to-disk")
        && runbook.contains("extract-boot")
        && runbook.contains("El Torito")
        && runbook.contains("docs/evidence/r640")
        && runbook.contains("Latitude / QEMU")
        && evidence.contains("SHA256")
        && evidence.contains("Serial excerpt")
        && evidence.contains(M7_ISO_INSTALL_OK_MARKER)
        && evidence.contains("reboot-to-disk")
        && status.contains("STATUS=closed")
        && status.contains(M7_ISO_INSTALL_OK_MARKER)
        && status.contains("scaffold")
}

/// Full M7.7 scaffold package prop.
pub fn prop_iso_install_scaffold_package() -> bool {
    let _ = (ISO_INSTALL_GAP_NOTE, ISO_INSTALL_HOST_LIMIT_NOTE);
    iso_install_surface_present()
        && iso_install_honesty_holds()
        && iso_install_scripts_present()
        && prop_iso_install_package()
}

/// Full M7.7 scaffold gate.
pub fn run_m7_iso_install_scaffold_gate() -> bool {
    prop_iso_install_scaffold_package()
}

#[cfg(test)]
#[path = "m7_iso_install_gate_test.rs"]
mod m7_iso_install_gate_test;
