//! M7.7 ISO install-to-disk scaffold / package gate (outside Proven Core).
//!
//! Pillar: [Z] [A]
//! Proven Core: **outside** (ADR-009)
//!
//! Proves runbook + evidence template + install package exist.
//! Does **not** print `RAYNU-V-M7-ISO-INSTALL-OK` from host/CI — that marker
//! is reserved for QEMU/iron install-to-disk + reboot-to-disk proof.

use super::iso_install::{
    install_launch_surfaces_present, prop_iso_install_lab_package, prop_iso_install_package,
    prop_iso_reboot_lab_package, ISO_INSTALL_GAP_NOTE, ISO_INSTALL_HOST_LIMIT_NOTE,
    ISO_INSTALL_MVP_NOTE, M7_ISO_INSTALL_OK_MARKER, M7_ISO_INSTALL_SCAFFOLD_MARKER,
};

/// Host / CI marker when the M7.7 scaffold package passes.
pub const M7_ISO_INSTALL_GATE_MARKER: &str = M7_ISO_INSTALL_SCAFFOLD_MARKER;

/// True when iso_install module exposes package + markers + closed GAP.
pub fn iso_install_surface_present() -> bool {
    let s = include_str!("iso_install.rs");
    s.contains("fn prop_iso_install_package(")
        && s.contains("fn begin_install_to_disk(")
        && s.contains("fn launch_contract(")
        && s.contains("fn arm_install_launch_contract(")
        && s.contains("fn arm_lab_install_contract(")
        && s.contains("fn disk_bytes_for_virtio_launch(")
        && s.contains("fn note_reboot_pending_lab(")
        && s.contains("fn probe_iso_install_lab_flag(")
        && s.contains("fn probe_iso_reboot_lab_flag(")
        && s.contains("fn probe_iso_persist_reboot(")
        && s.contains("fn probe_product_linux_iso(")
        && s.contains("fn present_product_iso_if_retained(")
        && s.contains("fn stage46_hold_e4_shell(")
        && s.contains("fn retain_product_iso_bytes(")
        && s.contains("fn persist_armed_install_to_esp(")
        && s.contains("fn fill_persist_image(")
        && s.contains("fn prop_iso_reboot_lab_package(")
        && s.contains("fn mark_disk_written(")
        && s.contains("fn mark_reboot_pending(")
        && s.contains("fn mark_booted_from_disk(")
        && s.contains("fn dispatch_iso_install_rest(")
        && s.contains("fn product_iso_continues_past_eltorito(")
        && s.contains("fn stage46_host_never_prints_iso_install_ok(")
        && s.contains(M7_ISO_INSTALL_OK_MARKER)
        && s.contains(M7_ISO_INSTALL_SCAFFOLD_MARKER)
        && s.contains(ISO_INSTALL_GAP_NOTE)
        && s.contains(ISO_INSTALL_MVP_NOTE)
        && ISO_INSTALL_GAP_NOTE.contains("CLOSED M7.7")
        && include_str!("../src/main.rs").contains("disk_bytes_for_virtio_launch")
        && include_str!("../src/main.rs").contains("E5 install-sized virtio-blk")
        && include_str!("../src/main.rs").contains("probe_iso_install_lab_flag")
        && include_str!("../src/main.rs").contains("probe_iso_reboot_lab_flag")
        && include_str!("../src/main.rs").contains("probe_product_linux_iso")
        && include_str!("../src/main.rs").contains("stage46_hold_e4_shell")
        && include_str!("../tools/run-qemu.sh").contains("PRODUCT_ISO")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("--linux-iso")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("--no-linux-iso")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("pruning leftover ESP ISOs")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("ESP free=")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("fsck.vfat -a")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("not format")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("--refat-cruzer")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("mkfs.vfat -I -F 32 -n")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("fat_bytes_too_small")
        && include_str!("../tools/flash-cruzer-esp.sh").contains("re-run with --refat-cruzer")
        && include_str!("../devices/guest_irq.rs").contains("fn take_inject_vector(")
        && include_str!("../devices/guest_irq.rs").contains("VIRTIO_GSI")
        && include_str!("../devices/guest_irq.rs").contains("VIRTIO_ISO_GSI")
        && include_str!("../devices/guest_irq.rs").contains("raise_gsi(VIRTIO_PIC_IRQ)")
        && include_str!("../devices/guest_irq.rs").contains("fn raise_pit(")
        && include_str!("../devices/guest_irq.rs").contains("fn take_ioapic_vector(")
        && include_str!("../devices/guest_irq.rs").contains("fn ioapic_eoi(")
        && include_str!("../devices/guest_irq.rs").contains("RTE_REMOTE_IRR")
        && include_str!("../devices/lapic_virt.rs").contains("fn latch_irr(")
        && include_str!("../vmx/guest_uefi.rs").contains("take_ioapic_vector()")
        && include_str!("../devices/guest_irq.rs").contains("PIT_IRQ")
        && include_str!("../devices/guest_platform.rs").contains("fn pit_tick(")
        && include_str!("../devices/guest_platform.rs").contains("fn pit_write_data(")
        && include_str!("../devices/guest_platform.rs").contains("pit_access")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub rex:")
        && include_str!("../vmx/guest_uefi.rs").contains("try_inject_guest_irq")
        && include_str!("../vmx/guest_uefi.rs").contains("raise_pit()")
        && include_str!("../vmx/guest_uefi.rs").contains("ept_install_ioapic_trap")
        && include_str!("../vmx/guest_uefi.rs").contains("handle_uart_product")
        && include_str!("../devices/guest_uart.rs").contains("fn reassert_irq(")
        && include_str!("../devices/guest_uart.rs").contains("UART reassert RX not THRE")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_virtio_drain_every_resume")
        && include_str!("../vmx/guest_uefi.rs").contains("virtio drain every resume")
        && include_str!("../vmx/guest_uefi.rs").contains("linux virtio DRIVER_OK")
        && include_str!("../devices/guest_acpi.rs").contains("product ISO fw_cfg ACPI MADT")
        && include_str!("../devices/guest_platform.rs").contains("iso=0 named files stay 3")
        && include_str!("../devices/guest_platform.rs").contains("fw_len: u16")
        && include_str!("../vmx/guest_uefi.rs").contains("product ISO fw_cfg ACPI MADT (iso=0 named files stay 3)")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_pic_before_lapic")
        && include_str!("../vmx/guest_uefi.rs").contains("linux PIC before LAPIC")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_pic_irq0_vec")
        && include_str!("../vmx/guest_uefi.rs").contains("linux PIC IRQ0")
        && include_str!("../devices/guest_acpi.rs").contains("MADT IRQ0 ISO GSI 2")
        && include_str!("../devices/guest_acpi.rs").contains("DSDT PCI0 _PRT")
        && include_str!("../devices/guest_acpi.rs").contains("DSDT PCI0 _CRS")
        && include_str!("../devices/ide_cdrom.rs").contains("fn linux_hides_duplicate_slot0_ide")
        && include_str!("../devices/ide_cdrom.rs").contains("linux hides duplicate slot0 IDE")
        && include_str!("../devices/ide_cdrom.rs").contains("fn linux_hides_piix_ide")
        && include_str!("../devices/ide_cdrom.rs").contains("linux hides PIIX IDE")
        && include_str!("../devices/ide_cdrom.rs").contains("fn linux_ata_floating_bus")
        && include_str!("../devices/ide_cdrom.rs").contains("linux ATA floating bus")
        && include_str!("../boot/serial.rs").contains("fn linux_high_half")
        && include_str!("../vmx/guest_uefi.rs").contains("linux high-half hides PIIX")
        && include_str!("../devices/guest_irq.rs").contains("PIT skips IOAPIC pin 0")
        && include_str!("../devices/guest_irq.rs").contains("fn raise_pic_irq")
        && include_str!("../devices/guest_irq.rs").contains("fn ioapic_gsi2_armed")
        && include_str!("../devices/guest_irq.rs").contains("linux GSI 2 before PIC")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_pit_skips_ioapic_pin0")
        && include_str!("../vmx/guest_uefi.rs").contains("PIT skips IOAPIC pin 0")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_gsi2_before_pic")
        && include_str!("../vmx/guest_uefi.rs").contains("linux GSI 2 before PIC")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_fwcfg_string_fills_ram")
        && include_str!("../vmx/guest_uefi.rs").contains("fw_cfg IoReadFifo8")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_io_string_dest_ok")
        && include_str!("../vmx/guest_uefi.rs").contains("fw_cfg string skip HV identity dest=")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_fwcfg_identity_overlay")
        && include_str!("../vmx/guest_uefi.rs").contains("fw_cfg identity overlay")
        && include_str!("../vmx/guest_uefi.rs").contains("HV identity PML4 0x400000")
        && include_str!("../vmx/guest_uefi.rs").contains("PEI dest holds ACPI tables")
        && include_str!("../devices/guest_platform.rs").contains("fn is_fwcfg_data_port")
        && include_str!("../devices/guest_platform.rs").contains("fn is_acpi_pm1_io")
        && include_str!("../devices/guest_platform.rs").contains("PIIX4 PM1 SCI_EN")
        && include_str!("../devices/guest_irq.rs").contains("fn raise_ioapic_gsi")
        && include_str!("../devices/guest_irq.rs").contains("fn pic_has_deliverable")
        && include_str!("../devices/guest_irq.rs").contains("fn take_pic_vector")
        && include_str!("../devices/guest_uart.rs").contains("fn poll_host_rx(")
        && include_str!("../boot/serial.rs").contains("fn try_read_byte(")
        && include_str!("iso_install.rs").contains("fn patch_iso_linux_serial_console(")
        && include_str!("iso_install.rs").contains("squashfs,virtio_blk console=ttyS0")
        && include_str!("iso_install.rs").contains("ISO_GRUB_LINUX_FROM")
        && include_str!("iso_install.rs").contains("fn bump_iso9660_grub_cfg_size(")
        && include_str!("iso_install.rs").contains("ISO_GRUB_CFG_PATCHED_SIZE")
        && include_str!("iso_install.rs").contains("lpj=4194304")
        && include_str!("iso_install.rs").contains("no_timer_check")
        && include_str!("iso_install.rs").contains("tsc=reliable")
        && include_str!("iso_install.rs").contains("clocksource=tsc")
        && include_str!("iso_install.rs").contains("idle=poll")
        && include_str!("iso_install.rs").contains("earlycon=uart8250,io,0x3f8")
        && include_str!("iso_install.rs").contains("earlycon=uart8250,io,0x3f8 alpine_dev=vdb")
        && include_str!("iso_install.rs").contains("linux-line alpine_dev=vdb")
        && include_str!("iso_install.rs").contains("linux-line virtio_pci")
        && include_str!("iso_install.rs").contains("modules=loop,squashfs,virtio_pci,virtio_blk")
        && include_str!("iso_install.rs").contains("console=tty0")
        && include_str!("../vmx/guest_uefi.rs").contains("fn copy_guest_linear_one_page(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn copy_flash_at(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_flash_off(")
        && include_str!("../vmx/guest_uefi.rs").contains("FLASH_HPA")
        && include_str!("../vmx/guest_uefi.rs").contains("fn xapic_fetch_miss_eax_fallback(")
        && include_str!("../vmx/guest_uefi.rs").contains("skip-len is 1–15 even if peek got bytes")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_insn_linear(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_mmio_peek_linear(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn copy_mmio_insn(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_mmio_skip_len(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_decoded_len(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_effective_len(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn try_alloc_product_iso_install_disk(")
        && include_str!("../vmx/guest_uefi.rs").contains("Reserve the install disk first")
        && include_str!("../vmx/guest_uefi.rs").contains("Arm the product ISO window")
        && include_str!("../vmx/guest_uefi.rs").contains("PRODUCT_ISO_DISK_LEAVE_2M_SLOTS")
        && include_str!("../vmx/guest_uefi.rs").contains("256MiB disk leftover report-RAM")
        && include_str!("../devices/guest_platform.rs").contains("TMR2_OUT")
        && include_str!("iso_install.rs").contains("fn product_iso_install_disk_try_sizes(")
        && include_str!("iso_install.rs").contains("fn product_iso_frame_pool_prefer_end(")
        && include_str!("../boot/handoff.rs").contains("fn take_report_ram_extra_2m(")
        && include_str!("../boot/handoff.rs").contains("fn seed_report_ram_extra(")
        && include_str!("../boot/mem.rs").contains("fn pick_conventional_region_above(")
        && include_str!("../boot/mem.rs").contains("fn pick_conventional_region_above_prefer(")
        && include_str!("../boot/mem.rs").contains("fn conventional_pages_above(")
        && include_str!("../boot/handoff.rs").contains("report-RAM extra skip")
        && !include_str!("../boot/handoff.rs").contains("report-RAM extra skip nested")
        && include_str!("../boot/handoff.rs").contains("nested product-ISO HOLDS")
        && include_str!("../tools/run-qemu.sh").contains("QEMU_MEM")
        && include_str!("../tools/run-qemu.sh").contains("2560M")
        && include_str!("../tools/e5-product-iso-qemu-serial.sh").contains("RAYNU-V-M1-VMXON-SKIP")
        && include_str!("../tools/e5-product-iso-qemu-serial.sh").contains("report-RAM extra hpa=")
        && include_str!("../boot/handoff.rs").contains("conventional above PRECISE pages=")
        && include_str!("../boot/handoff.rs").contains("REPORT_RAM_EXTRA_WANT_PAGES")
        && include_str!("../vmx/guest_uefi.rs").contains("no-zero")
        && include_str!("../vmx/guest_uefi.rs").contains("extra=")
        && include_str!("../vmx/guest_uefi.rs").contains("GUEST_UEFI_REPORT_RAM_PRODUCT_EXTRA: usize = 976")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_pf_should_deliver_to_guest(")
        && include_str!("../vmx/guest_uefi.rs").contains("#PF linux deliver")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_pf_entry_info(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_pf_blocks_irq(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_exception_bitmap(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_exc_blocks_irq(")
        && include_str!("../vmx/guest_uefi.rs").contains("LINUX_EXCEPTION_BITMAP")
        && include_str!("../vmx/guest_uefi.rs").contains("VM_ENTRY_EXCEPTION_ERROR_CODE")
        && include_str!("../arch/cpu.rs").contains("fn write_cr2(")
        && include_str!("iso_install.rs").contains("fn iso_text_context(")
        && include_str!("iso_install.rs").contains("uncompression error")
        && include_str!("iso_install.rs").contains("alpine-virt `grub.cfg`")
        && include_str!("../boot/handoff.rs").contains("frame pool product-ISO iron")
        && include_str!("../arch/cpu.rs").contains("fn host_hypervisor_present(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_insn_bytes_this_page(")
        && include_str!("iso_install.rs").contains("ata_piix,loop,sr-mod")
        && include_str!("iso_install.rs").contains("alpine_dev=vdb")
        && include_str!("iso_install.rs").contains("terminal_output serial ")
        && include_str!("iso_install.rs").contains("set timeout=1")
        && include_str!("iso_install.rs").contains("insmod efi_gop")
        && include_str!("iso_install.rs").contains("insmod all_video")
        && include_str!("iso_install.rs").contains("terminal_output console")
        && include_str!("../vmx/guest_uefi.rs").contains("fn handle_xapic_ept(")
        && include_str!("../vmx/guest_uefi.rs").contains("xAPIC 4K trap")
        && include_str!("../devices/lapic_virt.rs").contains("fn poll_timer_expiry(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_ADD")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SUB")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub cmp_reg_left:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub alu_reg_left:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_NOT")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_ADC")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SBB")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SHL")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_shift_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_shift(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_cc_taken(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_apply_cc(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_BSF")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_HINT")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_scan_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_hint(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_scan(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_TZCNT")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_tzcnt_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_count_zero(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_POPCNT")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_popcnt(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_PUSH")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_stack_width(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_stack_push(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_push(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_pop(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_MOVS")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_alu_is_string(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_CMPS")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SCAS")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SSE")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_alu_is_sse(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_sse_from_mem(")
        && include_str!("../vmx/guest_uefi.rs").contains("SAVED_XMM")
        && include_str!("../vmx/guest_uefi.rs").contains("movdqu")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_sse(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_xmm_in(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_string_step(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_IMUL")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_imul_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_imul(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_MUL")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_mul_pair_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_mul_pair(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_DIV")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_div_apply(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_DIV_DE_INTR_INFO")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MOVNTI")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_div_pair(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn inject_mmio_div_de(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_SHLD")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_double_shift_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_is_double_shift(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_alu_apply_cf(")
        && include_str!("../vmx/guest_uefi.rs").contains("mmio_alu_apply_cf(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_alu_rflags(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_alu_result(")
        && include_str!("../vmx/guest_uefi.rs").contains("armed product ISO uses")
        && include_str!("../vmx/guest_uefi.rs").contains("QEMU `PRODUCT_ISO=` can pass OVMF StartImage")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub bt:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_bt_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_apply_bt(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_CMPXCHG")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_CMPXCHG8B")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_cmpxchg8b_apply(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_apply_atomic(")
        && include_str!("../vmx/fields.rs").contains("CPU_BASED_CR8_LOAD_EXITING")
        && include_str!("../vmx/guest_uefi.rs").contains("CPU_BASED_CR8_STORE_EXITING")
        && include_str!("../devices/lapic_virt.rs").contains("fn set_cr8(")
        && include_str!("../vmx/guest_uefi.rs").contains("(8, 0)")
        && include_str!("../vmx/guest_uefi.rs").contains("| CPU_BASED_CR8_LOAD_EXITING")
        && !include_str!("../vmx/launch.rs").contains("| CPU_BASED_CR8_LOAD_EXITING")
        && include_str!("../devices/guest_serial_answer.rs").contains("mount -t iso9660 /dev/vdb")
        && include_str!("../devices/guest_serial_answer.rs").contains("mkdir -p /media/cdrom")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub test:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_test_rflags(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_apply_test_cmp(")
        && include_str!("../devices/guest_serial_answer.rs").contains("Stay in CONFIRM")
        && include_str!("../devices/guest_virtio_blk.rs").contains("pub xchg:")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_AND")
        && include_str!("../devices/ide_cdrom.rs").contains("31 * ISO_SECTOR")
        && include_str!("../devices/ide_cdrom.rs").contains("fn fill_read_drq")
        && include_str!("../devices/ide_cdrom.rs").contains("pkt_left")
        && include_str!("../devices/ide_cdrom.rs").contains("ATA_DEVCTL_NIEN")
        && include_str!("../devices/guest_virtio_blk.rs").contains("DATA_SEGS")
        && include_str!("../devices/guest_virtio_blk.rs").contains("GUEST_VIRTIO_ISO_PCI_DEV")
        && include_str!("../devices/guest_virtio_blk.rs").contains("VIRTIO_BLK_F_RO")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn page_left(")
        && include_str!("../devices/guest_serial_answer.rs").contains("fn note_tx(")
        && include_str!("../devices/guest_serial_answer.rs").contains("/ # ")
        && include_str!("../devices/guest_serial_answer.rs").contains("setup-disk -m sys -s 0 /dev/vda")
        && include_str!("../devices/guest_serial_answer.rs").contains("Which disk")
        && include_str!("../devices/guest_serial_answer.rs").contains("No disks available")
        && include_str!("../devices/guest_serial_answer.rs").contains("/media/cdrom/apks")
        && include_str!("../devices/guest_serial_answer.rs").contains("> /etc/apk/repositories")
        && include_str!("../devices/guest_serial_answer.rs").contains("How would you like")
        && include_str!("../devices/guest_serial_answer.rs").contains("modprobe virtio_pci")
        && include_str!("../devices/guest_serial_answer.rs").contains("modprobe sr_mod")
        && include_str!("../devices/guest_serial_answer.rs").contains("modprobe isofs")
        && include_str!("../devices/guest_serial_answer.rs").contains("mdev -s")
        && include_str!("../devices/guest_serial_answer.rs").contains("sleep 1")
        && include_str!("../devices/guest_serial_answer.rs").contains("[ -b /dev/vda ]")
        && include_str!("../devices/guest_serial_answer.rs").contains("|| mount -t iso9660 /dev/sr0")
        && include_str!("../vmx/guest_uefi.rs").contains("Lazy 2MiB WB map")
        && include_str!("../vmx/guest_uefi.rs").contains("fn report_ram_hpa_lookup_or_map")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_string_ins_needs_report_ram_map")
        && include_str!("../vmx/guest_uefi.rs").contains("GRUB `rep insw` into GCD heap never EPT-walks")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_tick_should_print")
        && include_str!("../vmx/guest_uefi.rs").contains("Linux printk ticks every 4096")
        && include_str!("../vmx/guest_uefi.rs").contains("guest UART nowait (do not clear COM2_LIVE)")
        && include_str!("../vmx/guest_uefi.rs").contains("guest UART TX ring drain")
        && include_str!("../vmx/guest_uefi.rs").contains("guest UART TX ring drain 4/exit")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon share TX ring")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon quiet ticks")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon hush HV")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon share product ISO")
        && include_str!("../vmx/guest_uefi.rs").contains("cpu_flush on tick cadence even when share")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon share first CPUID")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon share first high-half")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_earlycon_share_on_vmexit")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon share first bootimg")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_earlycon_share_on_bootimg")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon skip #PF dump")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon skip exc deliver")
        && include_str!("../vmx/guest_uefi.rs").contains("poll ISO-INSTALL-OK every resume")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_poll_iso_install_ok")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_earlycon_share_on_linux_deliver")
        && include_str!("../vmx/guest_uefi.rs").contains("write_line_nowait")
        && include_str!("../boot/serial.rs").contains("fn write_line_nowait")
        && include_str!("../boot/serial.rs").contains("linux earlycon hush HV")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_earlycon_drain")
        && include_str!("../vmx/guest_uefi.rs").contains("Linux CPUID GenuineIntel + NX")
        && include_str!("../boot/serial.rs").contains("fn write_byte_nowait")
        && include_str!("../boot/serial.rs").contains("fn drain_guest_tx")
        && include_str!("../boot/serial.rs").contains("GUEST_TX_DRAIN_EXIT")
        && include_str!("../boot/serial.rs").contains("guest UART TX drain COM2 independent")
        && include_str!("../boot/serial.rs").contains("fn guest_tx_sol_ready")
        && include_str!("../boot/serial.rs").contains("fn guest_tx_guest_lsr_thre")
        && include_str!("../boot/serial.rs").contains("linux earlycon pace LSR THRE")
        && include_str!("../vmx/guest_uefi.rs").contains("report-RAM EPT pre-map")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_report_ram_premap_gpa")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon EPT cap nowait")
        && include_str!("../vmx/guest_uefi.rs").contains("cpu_flush skip leftover pre-map")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_cpu_flush_skip_mapped")
        && include_str!("../vmx/guest_uefi.rs").contains("cpu-flush skip leftover pre-map")
        && include_str!("../vmx/guest_uefi.rs").contains("cpu_flush leftover per walk")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_cpu_flush_tick_scans_mapped")
        && include_str!("../vmx/guest_uefi.rs").contains("cpu_flush skip leftover pre-map on tick")
        && include_str!("../vmx/guest_uefi.rs").contains("linux unhandled nowait stop")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_unhandled_should_skip")
        && include_str!("../vmx/guest_uefi.rs").contains("fn virtio_mmio_eax_fallback")
        && include_str!("../vmx/guest_uefi.rs").contains("iso=0 decode fail still stops")
        && include_str!("../vmx/guest_uefi.rs").contains("fn virtio_mmio_retry_decode_len")
        && include_str!("../vmx/guest_uefi.rs").contains("linux MMIO decode retry")
        && include_str!("../vmx/guest_uefi.rs").contains("fn virtio_mmio_eax_fallback_len")
        && include_str!("../vmx/guest_uefi.rs").contains("linux EAX fallback skip 3")
        && include_str!("../vmx/guest_uefi.rs").contains("fn virtio_mmio_eax_fallback_size")
        && include_str!("../vmx/guest_uefi.rs").contains("virtio MMIO eax fallback size")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_virtio_mmio_polls_lapic")
        && include_str!("../vmx/guest_uefi.rs").contains("virtio MMIO polls lapic")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_io_raises_pit")
        && include_str!("../vmx/guest_uefi.rs").contains("linux I/O does not raise PIT")
        && include_str!("../vmx/guest_uefi.rs").contains("linux I/O does not raise PIT (iron MADT stop)")
        && include_str!("../vmx/guest_uefi.rs").contains("fn xapic_eax_fallback_skip_len")
        && include_str!("../vmx/guest_uefi.rs").contains("linux xAPIC EPT insn_len 0")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_preempt_deadloop_noskip")
        && include_str!("../vmx/guest_uefi.rs").contains("linux preempt deadloop noskip")
        && include_str!("../vmx/guest_uefi.rs").contains("linux_product_iso_raise_pit")
        && include_str!("../devices/guest_irq.rs").contains("fn prefer_pit_once")
        && include_str!("../devices/guest_irq.rs").contains("linux PIT prefer once")
        && include_str!("../devices/guest_irq.rs").contains("fn prefer_pit_until_driver_ok")
        && include_str!("../devices/guest_irq.rs").contains("linux PIT prefer until DRIVER_OK")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn virtio_needs_pit_over_uart")
        && include_str!("../vmx/guest_uefi.rs").contains("fn linux_prefer_pit_until_driver_ok")
        && include_str!("../vmx/guest_uefi.rs").contains("IOAPIC decode fail nowait")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_mov_dr_len")
        && include_str!("../vmx/guest_uefi.rs").contains("linux MOV DR skip")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_unhandled_try_skip")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_nmi_entry_info")
        && include_str!("../vmx/guest_uefi.rs").contains("linux NMI inject")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_virtio_bar_overlaps_scratch")
        && include_str!("../vmx/guest_uefi.rs").contains("virtio BAR trap over scratch")
        && include_str!("../vmx/guest_uefi.rs").contains("fn ept_split_2m_trap_4k")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_virtio_mmio_raises_pit")
        && include_str!("../vmx/guest_uefi.rs").contains("virtio MMIO raises PIT")
        && include_str!("../vmx/guest_uefi.rs").contains("virtio MMIO off=")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn common_cfg_byte")
        && include_str!("../devices/guest_virtio_blk.rs").contains("packed virtio common cfg")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn common_cfg_write_byte")
        && include_str!("../devices/guest_virtio_blk.rs").contains("packed virtio common cfg write")
        && include_str!("../devices/guest_platform.rs").contains("PIIX3 ISA BAR RAZ")
        && include_str!("../devices/guest_virtio_blk.rs").contains("fn mmio_programmed_bar_gpas")
        && include_str!("../boot/serial.rs").contains("fn write_str_nowait")
        && include_str!("../boot/serial.rs").contains("fn set_linux_earlycon_share")
        && include_str!("../devices/guest_uart.rs").contains("linux earlycon pace LSR THRE")
        && include_str!("../devices/guest_uart.rs").contains("Keep the 0x60/0x61 path until")
        && include_str!("../vmx/guest_uefi.rs").contains("linux earlycon pace LSR THRE")
        && include_str!("../vmx/guest_uefi.rs").contains("crate::boot::serial::guest_tx_clear()")
        && include_str!("../tools/qemu-boot-test.sh").contains("Kernel panic - not syncing")
        && include_str!("../boot/serial.rs").contains("Keep the port live")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_fixed_skip_len(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_cpuid_msr_skip(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_cpuid_force_skip(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_cpuid_exit_skip(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_filter_cpuid_for_linux(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_hpet_step_for_exit(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_hpet_uart_tsc_step")
        && include_str!("../vmx/guest_uefi.rs").contains("HPET TSC-delta on UART COM I/O")
        && include_str!("../devices/guest_platform.rs").contains("hpet_ticks_from_tsc_delta")
        && include_str!("../devices/guest_platform.rs").contains("HPET_UART_IO_STEP_CAP")
        && include_str!("../vmx/guest_uefi.rs").contains("HPET 1ms on CPUID/MSR/EPT")
        && include_str!("../devices/guest_platform.rs").contains("HPET_INSN_STEP")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_cpuid_leaf_is_hypervisor_scan(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_hypervisor_scan_bump_gpr(")
        && include_str!("../vmx/guest_uefi.rs").contains("GUEST_UEFI_LINUX_HYPERVISOR_SCAN_LAST")
        && include_str!("../vmx/guest_uefi.rs").contains("fn linux_hypervisor_scan_bump_native_cpuid_rbx_slot(")
        && include_str!("../vmx/guest_uefi.rs").contains("push %rbx")
        && include_str!("../vmx/guest_uefi.rs").contains("zero-extended")
        && include_str!("../vmx/guest_uefi.rs").contains("0xffff_8880")
        && include_str!("../vmx/guest_uefi.rs").contains("linux delay_loop skip")
        && include_str!("../vmx/guest_uefi.rs").contains("0x40003d00")
        && include_str!("../vmx/guest_uefi.rs").contains("0x4000bd00")
        && include_str!("../vmx/guest_uefi.rs").contains("GUEST_UEFI_CPUID_LEAF4_LAST_SUB")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_cpuid_should_log(")
        && include_str!("../vmx/guest_uefi.rs").contains("linux skip-2 force")
        && include_str!("../vmx/guest_uefi.rs").contains("GUEST_UEFI_IRON_LINUX_CPUID_RIP")
        && include_str!("../vmx/guest_uefi.rs").contains("linux cpuid")
        && include_str!("../vmx/guest_uefi.rs").contains("linux skip-2")
        && include_str!("../vmx/guest_uefi.rs").contains("0xA2 | 0x30 | 0x31 | 0x32 | 0x08 | 0x09")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_hlt_skip(")
        && include_str!("../vmx/guest_uefi.rs").contains("linux skip-1")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_linux_invlpg_len(")
        && include_str!("../vmx/guest_uefi.rs").contains("linux invlpg miss")
        && include_str!("../vmx/guest_uefi.rs").contains("Linux `delay_loop`")
        && include_str!("../vmx/guest_uefi.rs").contains("48 FF C8 75 FB")
        && include_str!("../vmx/guest_uefi.rs").contains("fn preempt_deadloop_delay_loop_skip_len(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn preempt_deadloop_delay_loop_sets_rax_one(")
        && include_str!("../vmx/guest_uefi.rs").contains("SAVED_RAX = 1")
        && include_str!("../vmx/fields.rs").contains("CPU_BASED_INVLPG_EXITING")
        && include_str!("../sched/msr_firewall.rs").contains("CPUID_LEAF7_EBX_CLWB")
        && include_str!("../vmx/guest_uefi.rs").contains("CPUID_LEAF7_EBX_CLWB")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_post_cd_non_io")
        && include_str!("../vmx/guest_uefi.rs").contains("fn mmio_near_xfer(")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_CALL")
        && include_str!("../devices/guest_virtio_blk.rs").contains("MMIO_ALU_JMP")
        && include_str!("../devices/guest_serial_answer.rs").contains("BOOTLOADER=grub")
        && include_str!("../devices/guest_serial_answer.rs").contains("USE_EFI=1")
        && include_str!("../devices/guest_serial_answer.rs").contains("BOOT_SIZE=48")
        && include_str!("../devices/guest_serial_answer.rs").contains("bootloader?")
        && include_str!("../devices/guest_serial_answer.rs").contains("[y/N]")
        && include_str!("../devices/guest_serial_answer.rs").contains("fn is_yes_prompt(")
        && include_str!("../devices/guest_serial_answer.rs").contains("setup-disk before apk update")
        && include_str!("../devices/guest_virtio_blk.rs").contains("ISO-INSTALL-OK on GPT not 16KiB")
        && include_str!("../devices/guest_virtio_blk.rs").contains("ISO_INSTALL_OK_MIN_OUT")
        && prop_iso_install_lab_package()
        && prop_iso_reboot_lab_package()
}

/// True when honesty + launch surfaces hold.
pub fn iso_install_honesty_holds() -> bool {
    ISO_INSTALL_HOST_LIMIT_NOTE.contains("cannot close")
        && ISO_INSTALL_MVP_NOTE.contains("reboot-to-disk")
        && M7_ISO_INSTALL_OK_MARKER == "RAYNU-V-M7-ISO-INSTALL-OK"
        && M7_ISO_INSTALL_SCAFFOLD_MARKER == "RAYNU-V-M7-ISO-INSTALL-SCAFFOLD-OK"
        && crate::mgmt::iso_install::stage46_host_never_prints_iso_install_ok()
        && crate::mgmt::iso_install::product_iso_continues_past_eltorito(false, true)
        && !crate::mgmt::iso_install::product_iso_continues_past_eltorito(true, true)
        && !crate::mgmt::iso_install::product_iso_len_is_window(
            crate::devices::ide_cdrom::GUEST_CD_ISO_CAP,
        )
        && crate::mgmt::iso_install::product_iso_len_is_window(
            crate::devices::ide_cdrom::GUEST_CD_ISO_CAP + 2048,
        )
        && install_launch_surfaces_present()
}

/// True when runbook + smoke + evidence template exist with required phrases.
pub fn iso_install_scripts_present() -> bool {
    let smoke = include_str!("../tools/m7-iso-install-smoke.sh");
    let runbook = include_str!("../docs/runbooks/iso_install.md");
    let evidence = include_str!("../docs/evidence/r640/TEMPLATE-iso-install.md");
    let status = include_str!("../docs/evidence/r640/STATUS-iso-install");
    smoke.contains(M7_ISO_INSTALL_SCAFFOLD_MARKER)
        && smoke.contains("m7_7_iso_install_scaffold_passes")
        && smoke.contains(M7_ISO_INSTALL_OK_MARKER)
        && smoke.contains("never print iron marker")
        && runbook.contains(M7_ISO_INSTALL_OK_MARKER)
        && runbook.contains(M7_ISO_INSTALL_SCAFFOLD_MARKER)
        && runbook.contains("reboot-to-disk")
        && runbook.contains("extract-boot")
        && runbook.contains("El Torito")
        && runbook.contains("docs/evidence/r640")
        && runbook.contains("Latitude / QEMU")
        && evidence.contains("SHA256")
        && evidence.contains("Serial excerpt")
        && evidence.contains(M7_ISO_INSTALL_OK_MARKER)
        && evidence.contains("reboot-to-disk")
        && status.contains("STATUS=closed")
        && status.contains(M7_ISO_INSTALL_OK_MARKER)
        && status.contains("scaffold")
}

/// Full M7.7 scaffold package prop.
pub fn prop_iso_install_scaffold_package() -> bool {
    let _ = (ISO_INSTALL_GAP_NOTE, ISO_INSTALL_HOST_LIMIT_NOTE);
    iso_install_surface_present()
        && iso_install_honesty_holds()
        && iso_install_scripts_present()
        && prop_iso_install_package()
}

/// Full M7.7 scaffold gate.
pub fn run_m7_iso_install_scaffold_gate() -> bool {
    prop_iso_install_scaffold_package()
}

#[cfg(test)]
#[path = "m7_iso_install_gate_test.rs"]
mod m7_iso_install_gate_test;
