//! M8.0 persist host gate (outside Proven Core).
//!
//! Pillar: [Z] [A]
//! Proven Core: **outside** (ADR-018)
//!
//! Proves the backend choice is written down, the iron marker is minted, and
//! the host GPT+ESP+ext4 round-trip exists. Does **not** print
//! `RAYNU-V-M7-ISO-INSTALL-OK` or the iron persist marker. Nested QEMU is
//! not this gate. Iron COM2 is not this gate.

use crate::mgmt::disk_persist::{
    esp_copy_is_rejected, host_never_prints_iso_install_ok, kind_survives_hv_reboot,
    select_persist_kind, PersistKind, ESP_COPY_REJECT_NOTE, M8_DISK_PERSIST_HOST_OK_MARKER,
    M8_DISK_PERSIST_OK_MARKER, PERC_UBUNTU_UNTOUCHED_NOTE, PERSIST_EXCLUSIVE_OWNERSHIP_NOTE,
    UDISK_TOO_SMALL_NOTE,
};
use crate::mgmt::durable_lun::durable_lun_policy_holds;

/// Host / CI marker when the M8.0 persist package passes.
pub const M8_DISK_PERSIST_GATE_MARKER: &str = M8_DISK_PERSIST_HOST_OK_MARKER;

/// Honesty: host round-trip ≠ nested Alpine kill/restart ≠ iron persist.
pub const M8_DISK_PERSIST_RESIDUAL_NOTE: &str =
    "residual: persist-first attach_disk_keep + host File round-trip is not nested Alpine kill/restart and not iron RAYNU-V-M8-DISK-PERSIST-OK; MODE=keep planted GPT keep=1 is not nested-OK; MODE=lunkeep/usbkeep planted DurableLun keep=1 is not nested-OK and not iron persist OK; DurableLun NVMe/USB I/O is not iron persist OK; leftover DRAM remains the fallback; M8_PERSIST_IMG file-RAM default off; distro OVMF ignores nvdimm/pc-dimm hotplug; tools/m8-persist-nested.sh is the nested two-boot harness; do not print ISO-INSTALL-OK";

/// True when plan, markers, leftover fallback, persist-first attach, and exclusive-ownership notes exist.
pub fn disk_persist_surface_present() -> bool {
    let persist = include_str!("disk_persist.rs");
    let plan = include_str!("../docs/m8_plan.md");
    let leftover = include_str!("iso_install.rs");
    let attach = include_str!("../vmx/guest_uefi.rs");
    let virtio = include_str!("../devices/guest_virtio_blk.rs");
    let handoff = include_str!("../boot/handoff.rs");
    let qemu = include_str!("../tools/run-qemu.sh");
    let nested = include_str!("../tools/m8-persist-nested.sh");
    let lun = include_str!("durable_lun.rs");
    persist.contains("enum PersistKind")
        && persist.contains("File")
        && persist.contains("DurableLun")
        && persist.contains("LeftoverDram")
        && persist.contains("fn select_persist_kind(")
        && persist.contains("fn restored_disk_is_installed(")
        && persist.contains("fn persist_media_looks_installed(")
        && persist.contains("fn choose_install_disk_attach(")
        && persist.contains("fn take_persist_install_disk(")
        && persist.contains("fn reserve_persist_install_disk(")
        && persist.contains("fn persist_install_disk_region(")
        && persist.contains("fn host_never_prints_iso_install_ok(")
        && persist.contains(M8_DISK_PERSIST_OK_MARKER)
        && persist.contains(M8_DISK_PERSIST_HOST_OK_MARKER)
        && persist.contains("RAYNU-V-M8-DISK-PERSIST-NESTED-OK")
        && persist.contains("ADR-004")
        && persist.contains("reset_keep_disk")
        && persist.contains("InstallDiskChoice::PersistKeep")
        && !persist.contains("println!(\"RAYNU-V-M7-ISO-INSTALL-OK\")")
        && !persist.contains("println!(\"RAYNU-V-M8-DISK-PERSIST-OK\")")
        && plan.contains("RAYNU-V-M8-DISK-PERSIST-OK")
        && plan.contains("RAYNU-V-M8-DISK-PERSIST-HOST-OK")
        && plan.contains("file-backed nested")
        && plan.contains("durable LUN")
        && plan.contains("DurableLun mapper")
        && plan.contains("leftover DRAM")
        && plan.contains("Force Off")
        && plan.contains("attach_disk_keep")
        && leftover.contains("fn carve_leftover_install_disk(")
        && leftover.contains("fn take_leftover_install_disk(")
        && attach.contains("fn try_alloc_product_iso_install_disk(")
        && attach.contains("take_leftover_install_disk")
        && attach.contains("take_persist_install_disk")
        && attach.contains("fn attach_persist_keep_on_vmx_skip(")
        && attach.contains("persist_lun_keep")
        && attach.contains("attach_disk_keep")
        && include_str!("../src/main.rs").contains("attach_persist_keep_on_vmx_skip(")
        && virtio.contains("fn attach_disk_keep(")
        && virtio.contains("fn attach_disk(")
        && virtio.contains("fn attach_lun(")
        && virtio.contains("allow_lun")
        && handoff.contains("PERSISTENT_MEMORY")
        && handoff.contains("leftover install disk skip persist")
        && handoff.contains("skip durable LUN")
        && handoff.contains("init_durable_lun_io")
        && qemu.contains("M8_PERSIST_IMG")
        && qemu.contains("M8_NVME_IMG")
        && qemu.contains("-device nvme")
        && qemu.contains("M8_USB_IMG")
        && qemu.contains("qemu-xhci")
        && qemu.contains("usb-storage")
        && qemu.contains("memory-backend=mem-m8-persist")
        && qemu.contains("memory-backend-file")
        && qemu.contains("+hypervisor")
        && !qemu.contains("-mem-path")
        && persist.contains("fn nested_promotes_leftover_to_file_persist(")
        && persist.contains("fn persist_lun_keep(")
        && persist.contains("fn persist_lun_keep_parts(")
        && persist.contains("fn persist_lun_last_gpt_err(")
        && include_str!("../raynu_f/gpt.rs").contains("fn find_esp_skip_array_crc<")
        && lun.contains("fn pick_durable_lun(")
        && lun.contains("fn classify_pci_storage(")
        && lun.contains("fn pci_is_perc(")
        && lun.contains("fn classify_usb_lun(")
        && lun.contains("fn durable_lun_can_virtio_attach(")
        && lun.contains("fn probe_durable_lun(")
        && lun.contains("fn r640_iron_lun_candidates(")
        && lun.contains("fn pci_storage_skip_note(")
        && lun.contains("fn durable_lun_need_media(")
        && lun.contains("DURABLE_LUN_NEED_MEDIA_NOTE")
        && lun.contains("skip ICH9 SATA")
        && lun.contains("skip AHCI")
        && lun.contains("PCI_SUBCLASS_NVME")
        && lun.contains("skip PERC")
        && lun.contains("no post-EBS I/O")
        && lun.contains("nvme I/O ready")
        && lun.contains("usb I/O ready")
        && lun.contains("fn init_durable_lun_io(")
        && lun.contains("fn init_durable_lun_usb_io(")
        && lun.contains("fn durable_lun_rw(")
        && lun.contains("fn durable_lun_512e_rw(")
        && lun.contains("fn durable_lun_read_any(")
        && lun.contains("LUN_CACHE_LINES")
        && include_str!("xhci.rs").contains("fn drain_events(")
        && include_str!("xhci.rs").contains("fn xhci_scratchpad_bufs(")
        && include_str!("xhci.rs").contains("fn xhci_run_usbcmd(")
        && include_str!("xhci.rs").contains("fn xhci_read_cap_snap(")
        && include_str!("xhci.rs").contains("fn xhci_scan_ports(")
        && include_str!("xhci.rs").contains("fn port_must_reset(")
        && include_str!("xhci.rs").contains("xhci hcrst")
        && include_str!("xhci.rs").contains("iface=08/06/50")
        && include_str!("xhci.rs").contains("fn parse_bot_eps(")
        && include_str!("xhci.rs").contains("XHCI_ENUM_CMD_SETCFG")
        && include_str!("xhci.rs").contains("xhci setcfg")
        && include_str!("xhci.rs").contains("fn control_nodata_retry(")
        && include_str!("xhci.rs").contains("fn bulk_ep_dci(")
        && include_str!("xhci.rs").contains("hcc1=0x")
        && include_str!("usb_bot.rs").contains("fn store_usb_bot_diag_unless_kept(")
        && include_str!("usb_bot.rs").contains("Do not send START STOP or")
        && include_str!("xhci.rs").contains("fn slot_ctx_dw0(")
        && include_str!("xhci.rs").contains("fn slot_ctx_dw1_port(")
        && include_str!("xhci.rs").contains("Root Hub Port Number")
        && !include_str!("xhci.rs").contains("u32::from(port) << 24 | u32::from(port) << 16")
        && include_str!("xhci.rs").contains("fn recover_enum(")
        && include_str!("xhci.rs").contains("fn abort_cmd_ring(")
        && include_str!("xhci.rs").contains("fn usb_dev_is_hub(")
        && include_str!("xhci.rs").contains("fn control_in_retry(")
        && include_str!("xhci.rs").contains("fn reset_ep0(")
        && include_str!("xhci.rs").contains("fn xhci_bring_up_keep_err(")
        && include_str!("xhci.rs").contains("XHCI_DESC_TRIES")
        && include_str!("xhci.rs").contains("USB_CLASS_HUB")
        && include_str!("xhci.rs").contains("hub skip")
        && include_str!("xhci.rs").contains("TRB_RESET_EP")
        && include_str!("xhci.rs").contains("TRB_STOP_EP")
        && include_str!("xhci.rs").contains("CMPL_CONTEXT_STATE")
        && include_str!("usb_bot.rs").contains("fn restore_usb_bot_diag(")
        && include_str!("xhci.rs").contains("fn xhci_ep_recover_need_reset(")
        && include_str!("usb_bot.rs").contains("USB_BOT_CMPL_CONTEXT_STATE")
        && include_str!("xhci.rs").contains("CMPL_TIMEOUT")
        && include_str!("xhci.rs").contains("ADDR_SPINS")
        && include_str!("xhci.rs").contains("BULK_SPINS")
        && include_str!("xhci.rs").contains("TRB_ISP")
        && include_str!("xhci.rs").contains("fn xhci_event_trb_ptr(")
        && include_str!("xhci.rs").contains("DESC_SPINS")
        && include_str!("xhci.rs").contains("XHCI_EP0_DCI")
        && include_str!("xhci.rs").contains("fn should_reset_ep0(")
        && include_str!("xhci.rs").contains("fn recover_ep(")
        && include_str!("xhci.rs").contains("cmd=4 cmpl=0xff")
        && include_str!("xhci.rs").contains("bot=? scsi=?")
        && include_str!("xhci.rs").contains("fn leftover_setup_event_does_not_retire_status_trb(")
        && include_str!("xhci.rs").contains("fn consume_control(")
        && include_str!("xhci.rs").contains("TRB_CH")
        && include_str!("xhci.rs").contains("TRB_EVALUATE_CTX")
        && include_str!("xhci.rs").contains("fn evaluate_ep0_mps(")
        && include_str!("xhci.rs").contains("fn toshiba_bot_eps(")
        && include_str!("xhci.rs").contains("fn usb_ep0_mps_from_desc(")
        && include_str!("xhci.rs").contains("USB_CFG_DESC_MPS")
        && include_str!("xhci.rs").contains("USB_CFG_DESC_MAX")
        && include_str!("xhci.rs").contains("fn usb_cfg_w_total(")
        && include_str!("xhci.rs").contains("fn read_bot_eps_or_toshiba(")
        && include_str!("xhci.rs").contains("xhci eval")
        && include_str!("xhci.rs").contains("xhci cfg-skip")
        && include_str!("xhci.rs").contains("fn setup_get_max_lun(")
        && include_str!("xhci.rs").contains("xhci maxlun")
        && include_str!("xhci.rs").contains(" skip (not ISO-INSTALL-OK)")
        && include_str!("xhci.rs").contains("Iron norearm COM2")
        && include_str!("xhci.rs").contains("Iron ep0-eval COM2")
        && include_str!("xhci.rs").contains("fn fill_config_ep_input(")
        && include_str!("xhci.rs").contains("fn config_ep_add_flags(")
        && include_str!("xhci.rs").contains("xhci epst")
        && include_str!("xhci.rs").contains("fn setup_msc_bot_reset(")
        && include_str!("xhci.rs").contains("xhci botrst")
        && include_str!("xhci.rs").contains("fn setup_clear_halt(")
        && include_str!("xhci.rs").contains("Iron maxlun COM2")
        && include_str!("xhci.rs")
            .contains("fn config_ep_input_copies_output_slot_and_clears_ep_state(")
        && include_str!("xhci.rs").contains("FIRST_READ_SPINS")
        && include_str!("xhci.rs").contains("xhci firstread")
        && include_str!("xhci.rs").contains("xhci firstcbw")
        && include_str!("xhci.rs").contains("norearm")
        && include_str!("xhci.rs").contains(" overlap (not ISO-INSTALL-OK)")
        && include_str!("xhci.rs").contains("fn consume_bulk_pair(")
        && include_str!("xhci.rs").contains("fn bulk_pair_take(")
        && include_str!("xhci.rs").contains("xhci capoverlap")
        && include_str!("xhci.rs").contains("Iron overlap COM2")
        && include_str!("xhci.rs").contains("Iron skipmaxlun COM2")
        && include_str!("xhci.rs").contains("Iron capoverlap COM2")
        && include_str!("xhci.rs").contains("fn cmd_cc_invalid(")
        && include_str!("xhci.rs").contains("xhci config p")
        && include_str!("xhci.rs").contains("xhci cfgretry")
        && include_str!("xhci.rs").contains("fn xhci_cmd_event_matches(")
        && include_str!("xhci.rs").contains("xhci cmdptr p")
        && include_str!("xhci.rs").contains("xhci toshiba p")
        && include_str!("xhci.rs").contains("fn xhci_enum_port_at(")
        && include_str!("xhci.rs").contains("xhci p11first")
        && include_str!("xhci.rs").contains("xhci abort crr=")
        && include_str!("xhci.rs").contains("xhci nop")
        && include_str!("xhci.rs").contains("xhci slotretry")
        && include_str!("xhci.rs").contains("xhci descabort")
        && include_str!("xhci.rs").contains("keep-slot (not Disable Slot")
        && include_str!("xhci.rs").contains("ep0 timeout (not Evaluate Context")
        && include_str!("xhci.rs").contains("fn xhci_desc_fail_stops_walk(")
        && include_str!("xhci.rs").contains("fn abort_keep_slot(")
        && include_str!("xhci.rs").contains("fn address_device(")
        && include_str!("xhci.rs").contains("fn get_device_desc(")
        && include_str!("xhci.rs").contains("fn xhci_keep_slot_after_desc(")
        && include_str!("xhci.rs").contains("fn xhci_guest_rw_long_wait(")
        && include_str!("xhci.rs").contains("fn xhci_rw_fail_should_print(")
        && include_str!("xhci.rs").contains("usb rw fail off=0x")
        && include_str!("xhci.rs").contains("scsi=")
        && include_str!("xhci.rs").contains("Iron descabort COM2")
        && include_str!("xhci.rs").contains("fn xhci_enum_diag_cmd(")
        && include_str!("xhci.rs").contains("Iron slotretry COM2")
        && include_str!("xhci.rs").contains("fn prime_cmd_ring(")
        && include_str!("xhci.rs").contains("fn enable_slot(")
        && include_str!("xhci.rs").contains("TRB_NO_OP_CMD")
        && include_str!("xhci.rs").contains("fn xhci_retry_enable_slot(")
        && include_str!("xhci.rs").contains("Iron p11first COM2")
        && include_str!("xhci.rs").contains("Iron cmdptr COM2")
        && include_str!("xhci.rs").contains("Iron firstcbw COM2")
        && include_str!("xhci.rs").contains("Iron epst COM2")
        && include_str!("xhci.rs").contains("Iron firstread COM2")
        && include_str!("usb_bot.rs").contains("fn prepare_first_cbw(")
        && include_str!("usb_bot.rs").contains("hw.prepare_first_cbw()")
        && include_str!("usb_bot.rs").contains("fn first_inquiry(")
        && include_str!("usb_bot.rs").contains("fn overlapped_in(")
        && include_str!("usb_bot.rs").contains("fn bot_inquiry_retry(")
        && include_str!("usb_bot.rs").contains("fn bot_in_retry(")
        && include_str!("usb_bot.rs").contains("hw.first_inquiry(")
        && include_str!("usb_bot.rs").contains("hw.overlapped_in(")
        && include_str!("usb_bot.rs").contains("fn prepare_first_read(")
        && include_str!("usb_bot.rs").contains("hw.prepare_first_read()")
        && include_str!("usb_bot.rs").contains("hw.end_first_read()")
        && include_str!("usb_bot.rs").contains("bot_inquiry_retry(hw, &mut tag, &mut inq)?;")
        && include_str!("usb_bot.rs")
            .contains("bot_in_retry(hw, &mut tag, &cdb_read_capacity10(), &mut cap)?;")
        && include_str!("xhci.rs").contains("bounce_in")
        && include_str!("xhci.rs").contains("BOT_SETTLE_SPINS")
        && include_str!("usb_bot.rs").contains("fn usb_bot_recover_after_fail(")
        && include_str!("usb_bot.rs").contains("USB_BOT_CMPL_TIMEOUT")
        && include_str!("usb_bot.rs").contains("fn bot_cmd_retry(")
        && include_str!("usb_bot.rs").contains("bot=csw scsi=capacity")
        && include_str!("usb_bot.rs").contains("bot=cbw scsi=capacity")
        && include_str!("usb_bot.rs").contains("cdb_inquiry()")
        && include_str!("usb_bot.rs").contains("fn settle(")
        && include_str!("xhci.rs").contains("fn reset_bulk_ep(")
        && include_str!("xhci.rs").contains("fn recover_pipes(")
        && include_str!("xhci.rs").contains("fn bulk_in_trb_flags(")
        && include_str!("xhci.rs").contains("bot=")
        && include_str!("durable_lun.rs").contains("scsi=")
        && include_str!("usb_bot.rs").contains("fn usb_bot_keep_xfer_diag(")
        && include_str!("usb_bot.rs").contains("fn usb_bot_scsi_name(")
        && include_str!("usb_bot.rs").contains("fn recover_pipes(")
        && include_str!("xhci.rs").contains("CRCR_CA")
        && include_str!("xhci.rs").contains("USB_MSC_UAS")
        && include_str!("xhci.rs").contains("fn cfg_msc_protos(")
        && include_str!("xhci.rs").contains("XHCI_PORT_SCAN_MAX")
        && include_str!("xhci.rs").contains("xhci enum p")
        && include_str!("xhci.rs").contains("XHCI_SCRATCH_MAX: u32 = 64")
        && include_str!("xhci.rs").contains("scratch=")
        && include_str!("xhci.rs").contains("USBLEGSUP_OS_OWNED")
        && include_str!("nvme.rs").contains("fn nvme_bring_up(")
        && include_str!("nvme.rs").contains("fn nvme_rw(")
        && include_str!("usb_bot.rs").contains("fn usb_bot_bring_up(")
        && include_str!("usb_bot.rs").contains("fn cdb_tur(")
        && include_str!("usb_bot.rs").contains("fn cdb_start_stop(")
        && include_str!("usb_bot.rs").contains("SCSI_START_STOP")
        && include_str!("usb_bot.rs").contains("USB_BOT_RW_TRIES")
        && include_str!("usb_bot.rs").contains("fn usb_bot_rw(")
        && include_str!("../vmx/guest_uefi.rs").contains("fn guest_uefi_virtio_stall_dump_frozen")
        && include_str!("xhci.rs").contains("fn xhci_init_pci(")
        && !lun.contains("println!(\"RAYNU-V-M8-DISK-PERSIST-OK\")")
        && !lun.contains("println!(\"RAYNU-V-M7-ISO-INSTALL-OK\")")
        && include_str!("../src/main.rs").contains("probe_durable_lun(")
        && handoff.contains("durable LUN not ready")
        && include_str!("../docs/runbooks/m8_persist_iron.md")
            .contains("durable LUN nvme I/O ready")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("xhci descabort")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("descabort COM2")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("usb rw fail")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("slotretry COM2")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("xhci slotretry")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("xhci nop")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("p11first COM2")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("Do not F11")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("never PERC")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("xhci cap caplen")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("cmpl=0x13")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("cmpl=0xff")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("hub skip")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("BULK_SPINS")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("bot=cbw|data|csw")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("scsi=")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("68e16633")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("0780df21")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("bot=cbw scsi=capacity")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("iface=08/06/50")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("consume_transfer")
        && include_str!("../docs/runbooks/m8_persist_iron.md").contains("Do not setup-disk")
        && include_str!("usb_bot.rs").contains("Hub = 9")
        && nested.contains("MODE=smoke")
        && nested.contains("MODE=full")
        && nested.contains("MODE=keep")
        && nested.contains("MODE=lun")
        && nested.contains("MODE=usb")
        && nested.contains("MODE=lunkeep")
        && nested.contains("MODE=usbkeep")
        && nested.contains("require_persist_gpt_in_file")
        && nested.contains("enable_shadow_vmcs=0")
        && nested.contains("plant_m8_persist_fixture")
        && nested.contains("plant_media_fixture")
        && nested.contains("M8_PERSIST_IMG")
        && nested.contains("file-RAM")
        && nested.contains("3584M")
        && nested.contains(r#"M8_PERSIST_SIZE="${M8_PERSIST_SIZE:-$QEMU_MEM}""#)
        && nested.contains("truncate -s \"$QEMU_MEM\"")
        && qemu.contains("file-RAM must match QEMU_MEM")
        && qemu.contains("growing M8_PERSIST_IMG")
        && nested.contains("max-ram-below-4g")
        && nested.contains("require_leftover_persist_disk")
        && nested.contains("67108864")
        && nested.contains("error: leftover/File persist disk is 64 MiB pool")
        && nested.contains("leftover install disk skip persist")
        && nested.contains("leftover install disk skip persist avail=")
        && nested.contains("leftover/File persist attached")
        && nested.contains("hpa=0x[0-9a-f]+ bytes=[0-9]+ \\(nested File RAM")
        && nested.contains("Installation is complete")
        && nested.contains("keep=1")
        && nested.contains("RAYNU-V-M8-DISK-PERSIST-NESTED-OK")
        && nested.contains("kill HV")
        && include_str!("../docs/runbooks/m8_persist_nested.md").contains("MODE=full")
        && include_str!("../docs/runbooks/m8_persist_nested.md").contains("3584M")
        && include_str!("../docs/evidence/nested/2026-09-13-ce3d8a09-m8-disk-persist-nested-ok.md")
            .contains("RAYNU-V-M8-DISK-PERSIST-NESTED-OK")
        && include_str!("../docs/evidence/nested/2026-09-13-ce3d8a09-m8-disk-persist-nested-ok.md")
            .contains("keep=1")
        && include_str!("../docs/evidence/nested/2026-09-13-ce3d8a09-m8-disk-persist-nested-ok.md")
            .contains("not ISO-INSTALL-OK")
        && !nested.contains("println!(\"RAYNU-V-M7-ISO-INSTALL-OK\")")
        && !nested.contains("echo \"RAYNU-V-M8-DISK-PERSIST-OK\"")
}

/// Host package: backend choice + leftover fallback + never ISO-INSTALL-OK.
pub fn run_m8_disk_persist_host_gate() -> bool {
    M8_DISK_PERSIST_GATE_MARKER == "RAYNU-V-M8-DISK-PERSIST-HOST-OK"
        && M8_DISK_PERSIST_OK_MARKER == "RAYNU-V-M8-DISK-PERSIST-OK"
        && host_never_prints_iso_install_ok()
        && select_persist_kind(true, true) == PersistKind::File
        && select_persist_kind(false, true) == PersistKind::DurableLun
        && select_persist_kind(true, false) == PersistKind::LeftoverDram
        && kind_survives_hv_reboot(PersistKind::File)
        && kind_survives_hv_reboot(PersistKind::DurableLun)
        && !kind_survives_hv_reboot(PersistKind::LeftoverDram)
        && esp_copy_is_rejected()
        && ESP_COPY_REJECT_NOTE.contains("installdisk.bin")
        && UDISK_TOO_SMALL_NOTE.contains("994 MiB")
        && PERC_UBUNTU_UNTOUCHED_NOTE.contains("PERC")
        && PERSIST_EXCLUSIVE_OWNERSHIP_NOTE.contains("ADR-004")
        && M8_DISK_PERSIST_RESIDUAL_NOTE.contains("ISO-INSTALL-OK")
        && durable_lun_policy_holds()
        && disk_persist_surface_present()
}

#[cfg(test)]
#[path = "m8_disk_persist_gate_test.rs"]
mod m8_disk_persist_gate_test;
